#!/bin/bash

# install usb notifications
cp 99-usb.rules /etc/udev/rules.d/
cp usbup /usr/local/bin

# set user to modify backlight HEL
if [ $HOSTNAME == "hel" ]
then
    #groupadd backlight
    usermod -aG backlight grzebiel
    chgrp -R backlight /sys/class/backlight/intel_backlight/brightness
    chmod g+w /sys/class/backlight/intel_backlight/brightness
fi

# set screenlock on suspend
cp sleep_lock.service /etc/systemd/system
systemctl daemon-reload
systemctl enable sleep_lock.service
