#!/bin/bash

# install usb notifications
sudo cp 99-usb.rules /etc/udev/rules.d/
sudo cp usbup /usr/local/bin

# set user to modify backlight HEL
if [ $HOSTNAME == "hel" ] || [ $HOSTNAME == "frigg" ]
then
    #groupadd backlight
    sudo usermod -aG video grzebiel

    #enable battery notifications
    systemctl --user enable battery-deamon.service
fi

# set screenlock on suspend
sudo cp sleep_lock.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl enable sleep_lock.service

# enable the ssh-agent
systemctl enable --user ssh-agent.service

# add modification rights brightness to video group via udev
sudo cp backlight.rules /etc/udev/rules.d

# keyd configuration
sudo cp keyd/default.conf /etc/keyd/default.conf
sudo systemctl enable keyd
sudo systemctl start keyd
sudo keyd reload

