#!/bin/bash

# install usb notifications
cp 99-usb.rules /etc/udev/rules.d/
cp usbup /usr/local/bin

# set user to modify backlight HEL
if [ $HOSTNAME == "hel" ]
then
    #groupadd backlight
    usermod -aG video grzebiel
fi

# set screenlock on suspend
cp sleep_lock.service /etc/systemd/system
systemctl daemon-reload
systemctl enable sleep_lock.service

# allow user to activate existing wifi profile
cp switch_wifi_to /usr/local/bin
echo "grzebiel ALL = NOPASSWD : /usr/local/bin/switch_wifi_to" > /etc/sudoers.d/10_switch_wifi_to
